### ISSUE TITLE
Binaries are not redistributable

### ISSUE THREAD

**Issue by 0u812** [SynBioDex/pySBOL#10]
_libsbol.so links to `/usr/local/opt/raptor/lib/libraptor2.0.dylib` which is a hard-coded path. Of course, the raptor library won't exist in that location on most users' machines. Please use static linking or rpaths so the binaries can be redistributed.

**Comment by 0u812** [comment]
On OS X btw

**Comment by bbartley** [comment]
Not sure why this happening just yet.  It links statically by default on Windows.  Probably there is a CMake flag somewhere that is missing.
I think that path is set by CMake's FindLibrary directive, and this path must be where Homebrew puts the raptor module.      From: Kyle Medley notifications@github.com
 To: SynBioDex/pysbol2 pysbol2@noreply.github.com 
 Sent: Friday, September 16, 2016 4:46 PM
 Subject: [SynBioDex/pysbol2] Binaries are not redistributable (#10)

_libsbol.so links to /usr/local/opt/raptor/lib/libraptor2.0.dylib which is a hard-coded path. Of course, the raptor library won't exist in that location on most users' machines. Please use static linking or rpaths so the binaries can be redistributed.—

**Comment by 0u812** [comment]
If there's a .a next to the .dylib you should be able to link to that 
instead.

J Kyle Medley, PhD Student
Bioengineering/BPSD, Sauro Lab
University of Washington, Seattle
p. (206) 659-9932
skype: jkylemedley
