### ISSUE TITLE
Autoconfigure certificate authorty path

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/pySBOL#105]
@bbartley has a fix for certificate authority path problems:

> Config.setOption('ca-path', path_to_ca_file)
>
> Where path_to_ca_file is defined as follows for different Linux distros:
> Debian/Ubuntu: "/etc/ssl/certs/ca-certificates.crt"
> Fedora/RHEL: "/etc/pki/tls/certs/ca-bundle.crt"
> OpenSUSE : "/var/lib/ca-certificates/ca-bundle.pem"

Can we have the library attempt to autoconfigure by checking the OS that it is running on?

**Comment by bbartley** [comment]
4758ce0 appears to have resolved this, have confirmed on Ubuntu and CentOS at least.

**Comment by bbartley** [comment]
Debian certificate path is incorrectly hardcoded

**Comment by bbartley** [comment]
Nevermind, the Debian certificate path is correct.
