### ISSUE TITLE
Enhancement request: Support for known cardinality

### ISSUE THREAD

**Issue by rpgoldman** [SynBioDex/pySBOL#110]
It seems that there are properties in SBOL that one may know to be singletons that are nevertheless internally represented as collections.  This leads to client code that relies on hard-coded `[0]` or `[-1]` references, which can be dangerously brittle.

The only defense the client programmer has against this issue is to remember to add assertions of the form `assert len(foo) == 1`, and even these are not fully satisfactory, since they detect failed assumptions only at runtime.

I don't know enough about the SBOL model to suggest fixes, but it would be very desirable to have something.

**Comment by jakebeal** [comment]
OBE, but I believe may be getting handled in pySBOL3 by https://github.com/SynBioDex/pySBOL3/issues/301
