### ISSUE TITLE
Handle sourceLocation values to support deletions.

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/pySBOL#111]
Issue #106 is about being able to split where something goes in a new genome using Location objects on a SequenceAnnotation.
This issue is the complement, about getting correct sequences from Location objects in the sourceLocation field of a Component.

For example, we should be able to pull a 2 kb insert construct out of a 5 kb plasmid by having a sourceLocation of e.g., 2001-4000.

Another example: replacing a 2 kb section of a genome might have a sourceLocation of 1-1000 and 3001-10000.

**Comment by bbartley** [comment]
ComponentDefinition.compile method can now sample subsequences of a subcomponent using SourceLocations, implemented in https://github.com/SynBioDex/libSBOL/pull/216/commits/23405c8b3040dc67c76a31cee0042ab66ac15555
