### ISSUE TITLE
Editing a Primary Structure error

### ISSUE THREAD

**Issue by dsanleo** [SynBioDex/pySBOL#119]
I'm executing your example to edit a Primary Structure

```
primary_structure = gene.getPrimaryStructure()
b0032_component = primary_structure[1]
gene.deleteUpstreamComponent(b0032_component)
r0011 = ComponentDefinition('r0011')
r0011.roles = SO_CDS
gene.insertUpstreamComponent(b0032_component, r0011)
```

but I got the following error:

AttributeError: 'ComponentDefinition' object has no attribute 'deleteUpstreamComponent'

I was looking for the function definition inside the API documentation but it is not there. How can I replace a component inside a primary structure?

**Comment by bbartley** [comment]
@dsanleo are you using the most recent version of pySBOL?
```
pip install pysbol --upgrade --user
```
You can see what version you are running:
```
pip show pysbol
```

**Comment by dsanleo** [comment]
I'm running the version 2.3.2.post4, the last version I found for windows 64bits. I didn´t use the Linux version yet.  If I use the Linux version 2.3.3, does this error disappear?

**Comment by bbartley** [comment]
I expect that the problem will disappear if you use Linux 2.3.3.  Also I will attempt to release updated 2.3.3 binaries for Windows over the next few days.  I don't usually have a Windows machine convenient, but it just so happens that I have a loaner laptop that I can use presently.

**Comment by dsanleo** [comment]
I just run he Linux 2.3.3 version and it works. For now I will use the linux version.
Thank you very much.
