### ISSUE TITLE
Typo in FunctionalComponent docstring

### ISSUE THREAD

**Issue by rpgoldman** [SynBioDex/pySBOL#120]
The docstring for `FunctionalComponent` seems to have been garbled, to the point where I'm not sure I  understand what it is trying to say:

```
class FunctionalComponent(ComponentInstance)
 |  The FunctionalComponent class is used to specify the functional usage of a
 |  ComponentDefinition inside a ModuleDefinition. The ModuleDefinition describes
 |  how the that describes how the FunctionalComponent interacts with others and
 |  summarizes their aggregate function.  
```

My guess is that should be "The ModuleDefinition describes how the FunctionalComponent interacts with others and summarizes their aggregate function."  Possibly also expand "their aggregate function" to "the aggregate function of the contained FunctionalComponents." -- the referent of "their" is not as clear as it could be.

**Comment by jakebeal** [comment]
Already fixed in referenced commit.
