### ISSUE TITLE
Support pip

### ISSUE THREAD

**Issue by kirichoi** [SynBioDex/pySBOL#13]
Support pip install for pySBOL on Windows, Mac and Linis

**Comment by hsauro** [comment]
By end of the year (2016)

**Comment by hsauro** [comment]
By end of February (2017) or sooner.

**Comment by bbartley** [comment]
@kirichoi I'm having difficulty building wheels with the versioning scheme we discussed.  For example, "2.1.1-0" and "2.1.1_0" both generate wheels named:

pySBOL-2.1.1.post0-cp27-none-any

Setuptools interprets these version strings as "post-releases".  https://www.python.org/dev/peps/pep-0440/#post-releases  which is not exactly the versioning semantic we want.  Any suggestions?  Maybe it's easier to leave the package versioning scheme as is?

**Comment by kirichoi** [comment]
How about using local version identifiers (https://www.python.org/dev/peps/pep-0440/#local-version-identifiers) Does that have any effect when uploaded to PyPI? When set, I am getting something like 

pySBOL-2.1.1+0-cp27-cp27m-win_amd64.whl

**Comment by kirichoi** [comment]
Also lets change Development Status to Production/Stable, i.e.

Development Status :: 5 - Production/Stable

**Comment by bbartley** [comment]
That looks good.  Will try it out.

**Comment by bbartley** [comment]
I tried registering a wheel using a local version identifier pySBOL-2.1.1+0 and got this error from PyPI:
HTTPError: 400 Client Error: version: Cannot use PEP 440 local versions. for url: https://upload.pypi.org/legacy/

**Comment by kirichoi** [comment]
Well that's a bummer. I wonder how matplotlib got 2.0.0-1 up on PyPi. Could it be a manual change?
Anyway, if nothing works, let's go with postfix notation, since that's what's intended for our purpose. 2.1.1.post0 is easier to understand than 2.1.1.0

**Comment by kirichoi** [comment]
Currently we support Python 2.7 and 3.6 for Windows 32 and 64 bit and Mac OSX 64 bit.

**Comment by matthiaskoenig** [comment]
Hi all, 
is it possible to also create the pip packages for linux and for py3.5?
Best 
Matthias

**Comment by kirichoi** [comment]
@matthiaskoenig: We are slowing working towards supporting linux. Building Linux pip distribution is surprisingly difficult, and we have to refactor some of our codes to make it happen.

**Comment by matthiaskoenig** [comment]
@kirichoi no problem. This has low priority. 
I am not working with SBOL right now, just wanted to get rid of the SBOL import warnings in tellurium for now.

**Comment by kirichoi** [comment]
For the record, I think manylinux1 distributions for Linux is now ready. Next release will include support for Linux systems through pip.

**Comment by jakebeal** [comment]
Long ago fixed.
