### ISSUE TITLE
Retrieving the names of SBOL roles

### ISSUE THREAD

**Issue by eyesmo** [SynBioDex/pySBOL#134]
Hi there,

I'm starting to do some genetic design with the Synthetic Biology Open Language (SBOL), and am starting to assign roles to components:

```
J23119_promoter.roles = SO_PROMOTER     #predefined constant, links to SO term 'promoter'
B0034_RBS.roles = SO_RBS                #predefined constant, links to SO term 'ribosome_entry_site'
spisPink_CDS.roles = SO_CDS             #predefined constant, links to 'CDS'
AF_SpisPink_Cassette.roles = [sb.SO + '0000352', sb.SO + '0000546'] #SO terms for 'DNA' and 'engineered sequence'
BsaI_bind.roles = sb.SO + '0000061' #SO term for restriction enzyme bind site   
BsaI_cutSite.roles = sb.SO + '0001975' #Term for restriction enzyme cut site that leaves a 5' overhang
```
I'm now trying to retrieve a string of the term describing the role of that object, but don't know the right way to do it. All I've been able to retrieve so far is the link to the term's webpage on the Sequence Ontology (identifiers.org/so/) website:

```
print(J23119_promoter.roles)
>> ['http://identifiers.org/so/SO:0000167']

print(AF_SpisPink_Cassette.roles)
>> ['http://identifiers.org/so/SO:0000352', 'http://identifiers.org/so/SO:0000546']
```
Now, I'm trying to do something like the inverse task, and to retrieve a string of the SO term's name (e.g. 'promoter', 'CDS', 'ribosome_entry_site', etc) from the SBOL 'roles' property. What's the best way to do this?

**Comment by jakebeal** [comment]
@bbartley's TYTO tool is designed to solve this problem, in both directions: https://github.com/SynBioDex/tyto

**Comment by eyesmo** [comment]
Thanks Jake!

**Comment by eyesmo** [comment]
Having a bit of trouble getting TYTO to work without throwing Lookup Errors:
```
uri = str(spacer3.roles[0])
SO.get_term_by_uri(uri)
>> LookupError: http://identifiers.org/so/SO:0002223 not found

SO.get_term_by_uri('http://identifiers.org/so/SO:0000352') #uri for generic DNA component
>> LookupError: http://identifiers.org/so/SO:0000352 not found

SO.get_term_by_uri('http://www.sequenceontology.org/miso/current_release/term/SO:0000352')
>> LookupError: http://www.sequenceontology.org/miso/current_release/term/SO:0000352 not found
```

**Comment by bbartley** [comment]
Try `https://identifiers.org/SO:0002223`

**Comment by jakebeal** [comment]
@bbartley It looks like the alternate (redundant) form that @eyesmo  is using is also supported by identifiers.org, so maybe TYTO should try to support that as well, even though it's not recommended?  In either case, this issue should probably be migrated to TYTO.

**Comment by eyesmo** [comment]
Will do, migrating now
