### ISSUE TITLE
Create documentation for pySBOL

### ISSUE THREAD

**Issue by kirichoi** [SynBioDex/pySBOL#14]
Create sphinx doc for pySBOL

**Comment by hsauro** [comment]
Waiting for ability to build python bindings on windows.

**Comment by hsauro** [comment]
At least one page with an example in sphinx.

**Comment by kirichoi** [comment]
Beta version on https://pysbol2.readthedocs.io/en/latest/index.html

**Comment by kirichoi** [comment]
Initial commit completed through 7a34ced63aaab92649d8d4594593e8696896f4ac
