### ISSUE TITLE
sbol.py

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL#19]
Add CMake directive to copy sbol.py and accompanying project files into each of the target build folders.  This will streamline the pip release process and reduce manual copying of files required to configure the pip package properly.

**Comment by bbartley** [comment]
libsbol commit b813af2 fixes this on Mac and Linux.  CMake build targets (x32, x64, Python2 and Python3) produce the proper folder configuration for pip deployment.  Still needs similar  implementation for Windows build.

**Comment by kirichoi** [comment]
Windows fix coming soon. BTW I was looking to the code and it seems like it's copying everything from pre-compiled code. I don't think this is the right way to do.

**Comment by kirichoi** [comment]
Commit SynBioDex/libSBOL@944dc23cdffeea5623b81dfbde9da650d2a9a9ce is for Windows

**Comment by kirichoi** [comment]
Commit SynBioDex/libSBOL@df1b561d2f8c0f2781bd701326374570c4923372 fix for Linux

**Comment by kirichoi** [comment]
Commit SynBioDex/libSBOL@75614a5978ab0828728c3af8e59735f4ba59ef19 should fix this for Mac. Please check.
