### ISSUE TITLE
Get CRISPR Tutorial for Python library working

### ISSUE THREAD

**Issue by hsauro** [SynBioDex/pySBOL#23]
Get CRISPR Tutorial for Python library working

**Comment by hsauro** [comment]
By Dec 7

**Comment by 0u812** [comment]
I'm not sure what the CRISPR tutorial is or what I have to do to get it working

**Comment by hsauro** [comment]
You were accidently put ont he issue, ignore it, it was reallocated to Kiri.

HErbert

**Comment by cjmyers** [comment]
Move the code into the tutorial document in overleaf and update text.

**Comment by kirichoi** [comment]
Tutorial document updated

**Comment by hsauro** [comment]
By Dec 21st of December
