### ISSUE TITLE
pySBOL crashing in Windows when using read()

### ISSUE THREAD

**Issue by kirichoi** [SynBioDex/pySBOL#24]
Currently, pySBOL crashes with reading SBOL documents.

**Comment by bbartley** [comment]
To my knowledge the Window binaries haven't been updated in a while.  There were some bugs with reading/writing that were resolved recently.  My most recent build on Mac appears to be working.

**Comment by kirichoi** [comment]
Fixed by updating raptor. I missed to set rdfxml and I think that caused the issue :p New Python binary installers for Windows incoming.
