### ISSUE TITLE
Catch exceptions in Python

### ISSUE THREAD

**Issue by kirichoi** [SynBioDex/pySBOL#25]
Currently, Python does not catch exceptions generated by the library. 
This is especially problematic when using something like IPython console, where there might be no messages to alert the users. Handling errors must be implemented better in Python libraries using fixed SWIG setup.

**Comment by bbartley** [comment]
libsbol a938514 added error handling to SWIG interface so that numeric error codes are propagated from C++ to Python

**Comment by kirichoi** [comment]
I'm reopening this because the error message is too basic i.e. it just returns something like 
`RuntimeError: 1`

**Comment by bbartley** [comment]
libsbol b612e33b should fix this.  error messages are no longer piped through stderr and should pass through to Python interpreter

**Comment by kirichoi** [comment]
Confirmed fixed
