### ISSUE TITLE
Methods componentDefinitions, moduleDefinitions, etc. are improperly implemented

### ISSUE THREAD

**Issue by kirichoi** [SynBioDex/pySBOL#26]
Methods such as componentDefinitions and moduleDefinitions are unreliable. Possibly due to SWIG wrapper.

**Comment by hsauro** [comment]
By Dec 21st.

**Comment by kirichoi** [comment]
This is caused by SBOL error 1, i.e.:

SBOL error 1:Object http://sbols.org/CRISPR_Example/ModuleDefinition/CRISPR_Template/1.0.0 not found

**Comment by kirichoi** [comment]
This is bit strange because the method should also look for http://sbols.org/CRISPR_Example/CRISPR_Template

**Comment by kirichoi** [comment]
This is probably coming from following sets of lines generated for .cxx file:

```
SWIGINTERN PyObject *_wrap_ownedModuleDefinition___getitem__(PyObject *self, PyObject *args) {
  Py_ssize_t argc;
  PyObject *argv[3] = {
    0
  };
  Py_ssize_t ii;
  
  if (!PyTuple_Check(args)) SWIG_fail;
  argc = args ? PyObject_Length(args) : 0;
  for (ii = 0; (ii < 2) && (ii < argc); ii++) {
    argv[ii] = PyTuple_GET_ITEM(args,ii);
  }
  if (argc == 2) {
    int _v;
    void *vptr = 0;
    int res = SWIG_ConvertPtr(argv[0], &vptr, SWIGTYPE_p_sbol__OwnedObjectT_sbol__ModuleDefinition_t, 0);
    _v = SWIG_CheckState(res);
    if (_v) {
      {
        int res = SWIG_AsVal_int(argv[1], NULL);
        _v = SWIG_CheckState(res);
      }
      if (_v) {
        return _wrap_ownedModuleDefinition___getitem____SWIG_0(self, args);
      }
    }
  }
  if (argc == 2) {
    int _v;
    void *vptr = 0;
    int res = SWIG_ConvertPtr(argv[0], &vptr, SWIGTYPE_p_sbol__OwnedObjectT_sbol__ModuleDefinition_t, 0);
    _v = SWIG_CheckState(res);
    if (_v) {
      int res = SWIG_AsPtr_std_string(argv[1], (std::string**)(0));
      _v = SWIG_CheckState(res);
      if (_v) {
        return _wrap_ownedModuleDefinition___getitem____SWIG_1(self, args);
      }
    }
  }
```

There are two `if (argc == 2)` arguments for some reason, but I cannot figure out where this is added from.
@bbartley : Any idea?

**Comment by bbartley** [comment]
In libsbol.i are there multiple instantiations of ownedModuleDefinitions? Note that SWIG issues a warning during the build process that some templates are instantiated twice.  I have always assumed this has no effect

**Comment by kirichoi** [comment]
None that I can immediately find of.

**Comment by kirichoi** [comment]
Ah, found it: documents.h line 539 to line 582

**Comment by bbartley** [comment]
Hmm.  I think I see a problem here.  The code block in 539-552 should execute regardless of how the previous if statement evaluates...in other words, it should not be contained in an else clause.  That could be the problem

**Comment by kirichoi** [comment]
This might be more of an issue of the fact that there are actually two get() functions.

**Comment by bbartley** [comment]
Are you referring to the following methods?
SBOLClass& OwnedObject<SBOLClass>::get(const std::string uri)SBOLSubClass& OwnedObject< SBOLClass >::get(std::string uri)

 
I don't suspect this to be a problem.  By default SWIG ignores these functions.  However, particular instantiations of these functions are declared in libsbol.i, so if this is indeed the problem, that's where I'd look for it.  You might try looking for template instantiations such as the following.  Perhaps there are some duplicate declarations causing the issue:
%template(addRange) sbol::OwnedObject::add<Range>;

**Comment by kirichoi** [comment]
This is getting really confusing. The problem is caused by the code automatically adding 'ModuleDefinition' for example, to URI. Remember where you implemented this?

**Comment by bbartley** [comment]
This behavior can be turned on and off by toggleSBOLCompliantTypes() and the current status of the flag can be checked by compliantTypesEnabled()
If there is an accessor method where it is not checking this flag, then it may be autoconstructing the URI incorrectly

**Comment by kirichoi** [comment]
Ah, now it makes sense. We should not implement toggleSBOLCompliantTypes() as a switch that can turn on and off. Set toggleSBOLCompliantTypes as a boolean which gets checked for it's value internally.

**Comment by kirichoi** [comment]
So I am testing out a new way to toggle SBOLCompliantTypes. The function will now accept boolean as optional argument. I will try to retain the original functionality. This will be applied to toggleSBOLCompliantTypes(), toggleSBOLCompliance(), and toggleExceptions().

**Comment by bbartley** [comment]
Eventually these should be deprecated and implemented using getOption and setOption (see issue tracker)

**Comment by kirichoi** [comment]
Sure, sounds good.
Commit SynBioDex/libSBOL@522ab6173d534e28dab8c4f36fcf23554321a75f fixes the issue for now.
