### ISSUE TITLE
readme code example: capitalized variables ...

### ISSUE THREAD

**Issue by graik** [SynBioDex/pySBOL#3]
a strictly cosmetic issue but capitalized variable names are quite un-pythonic :) first-letter capitalization is informally reserved for class names. All-capital constants are OK as well.

**Comment by bbartley** [comment]
I agree, the capitalized variable names are generally considered bad form in Python, but in this case it is a deliberate choice that helps distinguish SBOL definitions from instances.  Hence there are both CRISPRTemplate and crispr_template variables, for the Module Definition and the Module instance, respectively.  I am open to other conventions that help make these subtle nuances about SBOL more clear to the user.  And I do appreciate the advice about correct style!

**Comment by graik** [comment]
Ah, I see.
A perhaps better convention could be:

```
    crisprTemplate = ModuleDefinition(...
    _crisprTemplate = Module(...
```

or:

```
    crisprTemplate = ModuleDefinition(...
    crisprTemplate01 = Module(...
```

The latter highlighting that there could be more than one instance. Though
this may not work universally because devs may want to enumerate different
versions of MDef as well.

On Mon, Mar 28, 2016 at 10:03 PM, bbartley notifications@github.com wrote:

> I agree, the capitalized variable names are generally considered bad form
> in Python, but in this case it is a deliberate choice that helps
> distinguish SBOL definitions from instances.  Hence there are both
> CRISPRTemplate and crispr_template variables, for the Module Definition and
> the Module instance, respectively.  I am open to other conventions that
> help make these subtle nuances about SBOL more clear to the user.  And I do
> appreciate the advice about correct style!
> From: Raik Grünberg notifications@github.com
> To: SynBioDex/pysbol2 pysbol2@noreply.github.com
> Sent: Monday, March 28, 2016 11:41 AM
> Subject: [SynBioDex/pysbol2] readme code example: capitalized variables
> ... (#3)
> 
> a strictly cosmetic issue but capitalized variable names are quite
> un-pythonic :) first-letter capitalization is informally reserved for class
> names. All-capital constants are OK as well.—
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/SynBioDex/pysbol2/issues/3#issuecomment-202531862

## 

---

Raik Grünberg
http://www.raiks.de/contact.html

---

**Comment by hsauro** [comment]
Make sure examples are consitent.
