### ISSUE TITLE
Segfault when giving filename

### ISSUE THREAD

**Issue by 3ach** [SynBioDex/pySBOL#35]
Document.write() gives a segmentation fault when I try and write to a directory using tilde.

`doc.write('CRISPR.xml')` works, but `doc.write('~/CRISPR.xml')` throws a segfault.

**Comment by kirichoi** [comment]
My understanding is that ~ sign is terminal-specific and not natively supported by neither Python nor C++ to point to home directory. A fix is to add a path-checking sequence in Document.write() that automatically translates some symbols. We also need a default file extension to save the file as when the extension is not given

**Comment by kirichoi** [comment]
Moving to libSBOL repo
