### ISSUE TITLE
Need to discuss strategies for memory management

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL#39]
The following Python code causes null pointer exception, because garbage collector frees the C++ object when the `cdef' reference goes out of scope:
```
from sbol import *
doc = Document()
for i_cd in range(0,10):
    cdef = ComponentDefinition('%d' %i_cd)
    doc.addComponentDefinition(cdef)
doc.write()
```
A workaround is this:
```
from sbol import *
doc = Document()
for i_cd in range(0,10):
    cdef = ComponentDefinition('%d' %i_cd)
    cdef.thisown = False
    doc.addComponentDefinition(cdef)
doc.write()
```
But the implementation is not ideal.  Need to discuss the best strategy for memory management

**Comment by hsauro** [comment]
Check whether ComponentDefinition has refcount > 0 in the swg code when it is created, if not, inc refcount.

**Comment by bbartley** [comment]
Commit https://github.com/SynBioDex/libSBOL/commit/a0ae174ad7a569166f2a1efd87aa35543d06c247 of libsbol restores memory-management of SWIG-Python objects back to Python garbage collector

**Comment by kirichoi** [comment]
@bbartley Does the commit fix this issue?

**Comment by bbartley** [comment]
No it doesn't fix the issue.  It just rolls back the kludge I implemented previously to transfer responsibility for memory management to the user.  Because those changes would likely interfere with any attempts to manipulate the Python garbage collector

**Comment by hsauro** [comment]
In that case I imagine there is something wrong with the design. Can you show me the SWIG/Python code that creates

cdef = ComponentDefinition('%d' %i_cd)

**Comment by bbartley** [comment]
This is the C++ generated by SWIG that wraps the constructor...
```
SWIGINTERN PyObject *_wrap_new_ComponentDefinition(PyObject *self, PyObject *args) {
  Py_ssize_t argc;
  PyObject *argv[5] = {
    0
  };
  Py_ssize_t ii;
  
  if (!PyTuple_Check(args)) SWIG_fail;
  argc = args ? PyObject_Length(args) : 0;
  for (ii = 0; (ii < 4) && (ii < argc); ii++) {
    argv[ii] = PyTuple_GET_ITEM(args,ii);
  }
  if (argc == 0) {
    return _wrap_new_ComponentDefinition__SWIG_3(self, args);
  }
  if (argc == 1) {
    int _v;
    int res = SWIG_AsPtr_std_string(argv[0], (std::string**)(0));
    _v = SWIG_CheckState(res);
    if (_v) {
      return _wrap_new_ComponentDefinition__SWIG_2(self, args);
    }
  }
  if (argc == 2) {
    int _v;
    int res = SWIG_AsPtr_std_string(argv[0], (std::string**)(0));
    _v = SWIG_CheckState(res);
    if (_v) {
      int res = SWIG_AsPtr_std_string(argv[1], (std::string**)(0));
      _v = SWIG_CheckState(res);
      if (_v) {
        return _wrap_new_ComponentDefinition__SWIG_1(self, args);
      }
    }
  }
  if (argc == 3) {
    int _v;
    int res = SWIG_AsPtr_std_string(argv[0], (std::string**)(0));
    _v = SWIG_CheckState(res);
    if (_v) {
      int res = SWIG_AsPtr_std_string(argv[1], (std::string**)(0));
      _v = SWIG_CheckState(res);
      if (_v) {
        int res = SWIG_AsPtr_std_string(argv[2], (std::string**)(0));
        _v = SWIG_CheckState(res);
        if (_v) {
          return _wrap_new_ComponentDefinition__SWIG_0(self, args);
        }
      }
    }
  }
  if (argc == 4) {
    int _v;
    int res = SWIG_AsPtr_std_string(argv[0], (std::string**)(0));
    _v = SWIG_CheckState(res);
    if (_v) {
      int res = SWIG_AsPtr_std_string(argv[1], (std::string**)(0));
      _v = SWIG_CheckState(res);
      if (_v) {
        int res = SWIG_AsPtr_std_string(argv[2], (std::string**)(0));
        _v = SWIG_CheckState(res);
        if (_v) {
          int res = SWIG_AsPtr_std_string(argv[3], (std::string**)(0));
          _v = SWIG_CheckState(res);
          if (_v) {
            return _wrap_new_ComponentDefinition__SWIG_4(self, args);
          }
        }
      }
    }
  }
  
fail:
  SWIG_SetErrorMsg(PyExc_NotImplementedError,"Wrong number or type of arguments for overloaded function 'new_ComponentDefinition'.\n"
    "  Possible C/C++ prototypes are:\n"
    "    sbol::ComponentDefinition::ComponentDefinition(std::string,std::string,std::string)\n"
    "    sbol::ComponentDefinition::ComponentDefinition(std::string,std::string)\n"
    "    sbol::ComponentDefinition::ComponentDefinition(std::string)\n"
    "    sbol::ComponentDefinition::ComponentDefinition()\n"
    "    sbol::ComponentDefinition::ComponentDefinition(sbol::sbol_type,std::string,std::string,std::string)\n");
  return 0;
}
```

**Comment by hsauro** [comment]
Try this, from looking at the code it appears that ComponentDefinition can take zero arguments. If you call:

from sbol import *
doc = Document()
for i_cd in range(0,10):
    cdef = ComponentDefinition()
    doc.addComponentDefinition(cdef)
doc.write()

do you still get a memory problem?  If so can you replace

 return _wrap_new_ComponentDefinition__SWIG_3(self, args);

in line 14 with

ret  =   _wrap_new_ComponentDefinition__SWIG_3(self, args);
Py_INCREF(ret);
return ret

and see what happens.

**Comment by bbartley** [comment]
Hmm.  Unfortunately it's hard to do it exactly this way, due to the constraints of SWIG, but I get what you are trying to do.  It is probably easier to increment the reference using Python code.

I suspect this will fix the immediate problem, but then cause memory leaks elsewhere.

**Comment by hsauro** [comment]
But don't make the user have to manage memory, hide it.

**Comment by kirichoi** [comment]
Maybe something like this on libsbol.i might work?

https://stackoverflow.com/questions/25392139/swig-reference-count-error-with-python-callback

**Comment by hsauro** [comment]
Sounds promising.

Herbert

**Comment by kirichoi** [comment]
Are there any developments on this issue?

**Comment by bbartley** [comment]
A description of the problem can be found in the SWIG documentation [here](http://www.swig.org/Doc2.0/SWIGDocumentation.html#Python_nn30)

Specifically this example:
```
>>> v = Object()           # Create an object
>>> n = Node()             # Create a node
>>> n.set_value(v)         # Set value
>>> v.thisown
1
>>> del v
```
As they describe in the SWIG documentation, I'm attempting to implement a solution by dynamically setting the .thisown flag on objects as a user builds a Document.  This seems safer than directly working with the Python garbage collector.  However it leads to some additional challenges.

**Comment by kirichoi** [comment]
Currently, Document::close() method is ignored in the SWIG file. I will fix this and push the changes.

**Comment by kirichoi** [comment]
Also need to add docstrings for close() method.

**Comment by bbartley** [comment]
LibSBOL commit   https://github.com/SynBioDex/libSBOL/commit/02884765b6d8f805b04ed5ff7d43322cbd900873 fixes the double deletion error in the example.

This fix will introduce a memory leak when users remove objects from a Document.  Will open a new issue on libsbol for this.  Fortunately, this is an edge case that will not affect the majority of users.

**Comment by bbartley** [comment]
Closing this, because the problem is largely resolved.  However, some unlikely edge cases will result in a memory leak.  See https://github.com/SynBioDex/libSBOL/issues/140
