### ISSUE TITLE
Upload videos of compiling examples on different IDE tool

### ISSUE THREAD

**Issue by tramyn** [SynBioDex/pySBOL#43]
Note: This issue is paired with [libSBOL (C, C++)](https://github.com/SynBioDex/libSBOL/issues/142) and [libSBOLj (java)](https://github.com/SynBioDex/libSBOLj/issues/443), and [sbolj (javascript)](https://github.com/SynBioDex/sboljs/issues/10) library issue. 

This enhancement/request was brought up at COMBINE 2016. At the website breakout session, the community requested that it would be nice to have videos on how to compile a simple example using Visual Studio etc. for each library.

**Comment by jakebeal** [comment]
I believe this has been effectively addressed by Jupyter notebooks in recent tutorials.
