### ISSUE TITLE
Upload tutorial examples

### ISSUE THREAD

**Issue by tramyn** [SynBioDex/pySBOL#44]
Note: This issue is paired with [libSBOL (C, C++)](https://github.com/SynBioDex/libSBOL/issues/143) and [libSBOLj (java)](https://github.com/SynBioDex/libSBOLj/issues/444), and [sbolj (javascript)](https://github.com/SynBioDex/sboljs/issues/11) library issue.

This enhancement/request was brought up at COMBINE 2016. At the website breakout session, the community requested that it would be nice to put all documentation on github.io

For every language provide the following example:
i) Very simple gene cassette (See C/C++ example)
ii) Put together a toggle switch example
iii) CRISPR

Provide a developers FAQ. List simple operations, eg sequence create sequence, join parts etc, this should be for all languages

**Comment by jakebeal** [comment]
Moot, given the shift to pySBOL2 and pySBOL3
