### ISSUE TITLE
Add tests for iterators and memory management

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL#48]
Experience has shown that these SWIG-Python extensions are the most likely thing to break in the SWIG interface.

**Comment by kirichoi** [comment]
Simple memory test was implemented in commit https://github.com/SynBioDex/libSBOL/commit/5186f5fa9cff9434d2a4611a0bf47be311976dc3

**Comment by kirichoi** [comment]
Iterator test was implemented in commit https://github.com/SynBioDex/libSBOL/commit/3d07957e8db946806a2b45fc611b454019b7233e
