### ISSUE TITLE
Possible issue with reading files ?

### ISSUE THREAD

**Issue by rupalkhilari** [SynBioDex/pySBOL#5]
I am trying to use pysbol2 to parse the [CRISPR_example.xml](https://github.com/SynBioDex/libSBOL/blob/master/example/CRISPR_example.xml)  file. It seems like the data is not parsed and read into the required fields consistently. 

```
>>> import sbol
>>> d = sbol.Document()
>>> d.read('/tmp/CRISPR_example.xml')
>>> d.sequences
<Swig Object of type 'std::unordered_map< std::string,sbol::TopLevel * > *' at 0x10c9e7570>
>>> d.sequences.next()
>>> d.sequences.next()
>>> d.sequences.next()   # Unable to find any sequences within the document


>>> s = d.getSequence('http://sbols.org/sys-bio.org/Sequence/CRPbPromoterSeq/1.0.0')
>>> s
<sbol.libsbol.Sequence; proxy of <Swig Object of type 'sbol::Sequence *' at 0x10c9e7570> >
>>> s.displayId.get()   # Missing some information. 
''
>>> s.version.get()
''
>>> s.identity.get()
'http://sbols.org/sys-bio.org/Sequence/CRPbPromoterSeq/1.0.0'
```

I believe the `s.version` and `s.displayId` properties should also contain info as per the file. 
Am I missing something here ? I wasn't able to find any example where these elements have been extracted from an SBOL 2.0 file using pysbol2. 

I'd really appreciate any help.

Thank you.

PS: I am on Mac OS using libxml2-2.9.4 and raptor-2.0.15

**Comment by kirichoi** [comment]
The issue with missing displayId/version is fixed in the latest Windows release. Mac OSX release will to available soon.

Still investigating issue with missing sequences.
