### ISSUE TITLE
Refactor getAll() and getObjects() into a single method

### ISSUE THREAD

**Issue by kirichoi** [SynBioDex/pySBOL#52]
Method getAll() results in runtime error

**Comment by bbartley** [comment]
The following test passes on OS X:
```
>>> from sbol import *
>>> cd = ComponentDefinition('test')
>>> cd.roles.get()
''
>>> cd.roles.getAll()
('',)
>>> len(cd.roles.getAll())
1
```
For properties where you expect an object, use getObjects():
```
>>> from sbol import *
>>> cd = ComponentDefinition()
>>> cd.sequenceAnnotations.getObjects()
[]
```

It would be good if we could combine getAll() and getObjects() into a single method with the same name, but that would require some clever refactoring.

**Comment by kirichoi** [comment]
I see. I will be renaming this issue then.

**Comment by jakebeal** [comment]
Moot given the shift to pySBOL2.
