### ISSUE TITLE
sequences.get() defaults to wrong URI

### ISSUE THREAD

**Issue by kirichoi** [SynBioDex/pySBOL#55]
Document.sequences.get(), when reading a file, should follow the files URI but fails to do so.

Line in question:
https://github.com/SynBioDex/libSBOL/blob/develop/wrapper/unit_tests.py#L635

Test file:
https://github.com/SynBioDex/libSBOL/blob/develop/wrapper/test/SBOL2/roundTrip.xml#L156-L162

sequences.get() looks for object `http://examples.org/Sequence/CRP_b_seq/1.0.0` instead.

**Comment by kirichoi** [comment]
A workaround is to set correct homespace.

**Comment by kirichoi** [comment]
get() does not accept displayId anymore. Any idea how this happened?

**Comment by bbartley** [comment]
Fixed by https://github.com/SynBioDex/libSBOL/commit/3cd40054dc743f78c2f35de9c2e847f2f1cfb392
