### ISSUE TITLE
Example gene_cassette from https://pysbol2.readthedocs.io/en/latest/sbol_examples.html

### ISSUE THREAD

**Issue by JulesBobVerne** [SynBioDex/pySBOL#57]
Line 6 -> "gene_example" should be "gene"
Line 8 -> "cds" should be "CDS"

Line 23 -> "gene.assemble" function adds a "/0/" to the URI which results in invalid SBOL code

**Comment by kirichoi** [comment]
Thanks for reporting errors. The first two errors are fixed. The last issue seems like a bug in the library which will take a bit more time to fix.

**Comment by bbartley** [comment]
Fixed the last error on my machine.  Will push it soon.  It was actually pretty easy to fix

**Comment by bbartley** [comment]
Fixed by https://github.com/SynBioDex/libSBOL/commit/5fe023e7330b8b30ad5c0b348a5968e2e451a9a0
