### ISSUE TITLE
iterating over the types list of ComponentDefinition 

### ISSUE THREAD

**Issue by eoberortner** [SynBioDex/pySBOL#62]
I'm following the "Iterating and Indexing List Properties" example to iterate over the types of a ComponentDefinition. Here's my code:
        doc = Document()

        gene = ComponentDefinition("gene_example")
        gene.types.set(SO_GENE)
        doc.addComponentDefinition(gene)
        
        ## iterate over the CDs in the document
        for cd in doc.componentDefinitions:
            
            print('--------------------------')
            print('displayId: {}'.format(cd.displayId.get()))
            print('# of types: {}'.format(len(cd.types)))
            
            ## print the types of the CD
            ## the following code works:
            for i in range(0, len(cd.types)):
                print('{}-th type: {}'.format((i+1), cd.types[i]))
                
            ## the following code does NOT work
            for cd_type in cd.types.begin():
                print('type: {}'.format(cd_type))

Iterating over the list using an iterator results in the following error:
    for cd_type in cd.types.begin():
TypeError: 'SwigPyObject' object is not iterable

**Comment by bbartley** [comment]
There's an error in the documentation.  The proper syntax is as follows:
```
for cd_type in cd.types:
   print cd_type
```

**Comment by eoberortner** [comment]
I tried this solution too! However the following exception is thrown:
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/eoberortner/Projects/JGI/ORCA/coding/git/orca/tests/BuildSBOLTest.py", line 33, in test_create_CD_and_iterate_over_types
    for cd_type in cd.types:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sbol/libsbol.py", line 1870, in __next__
    return _libsbol.URIProperty___next__(self)
SystemError: <built-in function URIProperty___next__> returned a result with an error set

line 33 in my code is:
for cd_type in cd.types:

please let me know if you need any further information to reproduce this behavior!

**Comment by bbartley** [comment]
This is a bug in pySBOL for 3.5 and 3.6. Iterators work in 2.7.   I think I see the problem.

Will post a new PyPI distribution tonight or tomorrow.
