### ISSUE TITLE
Calling Document.getTopLevel() and Finding Nothing Causes Crash During Subsequent Write

### ISSUE THREAD

**Issue by nroehner** [SynBioDex/pySBOL#67]
Calling the getToplevel() method with a URI that doesn't exist in the Document causes a subsequent call of the write method to crash the program. For example,

doc = Document()

doc.componentDefinitions.create('ghost')

doc.getTopLevel('http://examples.org/ComponentDefinition/ghast/1.0.0')

doc.write(os.path.join(os.getcwd(), 'test.xml'))

**Comment by jakebeal** [comment]
Likely resolved long ago, and moot in any case given the shift to pySBOL2
