### ISSUE TITLE
Activity displayId field is modified 

### ISSUE THREAD

**Issue by mehersam** [SynBioDex/pySBOL#77]
Agent_act_assoc.xml
Provenance_CodonOptimization.xml
Provenance_SpecifyCutOperation_Ag_Act_CD.xml
Provenance_SpecifyCutOperation_*.xml
Was-generated-bys.xml

The displayId field has an extra "_activity"

**Comment by dsumorok-raytheon** [comment]
This was fixed in libSBOL by ea1bc89138e94e7cee913bad74ff8bb2f511d358.
