### ISSUE TITLE
CD ‘information’ nested annotations dropped

### ISSUE THREAD

**Issue by mehersam** [SynBioDex/pySBOL#78]
Annotation_Output.xml
[AnnotationOutput_file_comparisonErrors.txt](https://github.com/SynBioDex/pySBOL/files/2260518/AnnotationOutput_file_comparisonErrors.txt)

**Comment by dsumorok-raytheon** [comment]
This was fixed in the sbol library by 95cde9dea7c08be7f299c61579401a9298948227
