### ISSUE TITLE
VariableComponent version was inserted

### ISSUE THREAD

**Issue by mehersam** [SynBioDex/pySBOL#81]
[eukaryotic_promoters_enumerated_file_comparisonErrors.txt](https://github.com/SynBioDex/pySBOL/files/2260529/eukaryotic_promoters_enumerated_file_comparisonErrors.txt)
[eukaryotic_promoters_file_comparisonErrors.txt](https://github.com/SynBioDex/pySBOL/files/2260530/eukaryotic_promoters_file_comparisonErrors.txt)
[gfp_reporter_template_enumerated_file_comparisonErrors.txt](https://github.com/SynBioDex/pySBOL/files/2260531/gfp_reporter_template_enumerated_file_comparisonErrors.txt)
[gfp_reporter_template_file_comparisonErrors.txt](https://github.com/SynBioDex/pySBOL/files/2260532/gfp_reporter_template_file_comparisonErrors.txt)

**Comment by dsumorok-raytheon** [comment]
These errors were fixed in libSBOL by 95cde9dea7c08be7f299c61579401a9298948227.
