### ISSUE TITLE
Incomplete RDF is produced when using Python3

### ISSUE THREAD

**Issue by dissys** [SynBioDex/pySBOL#88]
The PySBOL library does not seem to generate full RDF/XML. I am not sure if it is me or something needs to be configured.

I have installed PySBOL manully using these steps
- git clone https://github.com/SynBioDex/pysbol.git
- cd pysbol
- python3 setup.py install

I then run the full example code at https://pysbol2.readthedocs.io/en/latest/sbol_examples.html#id1.

The resulting gene_cassette.xml is incomplete when I run "python3 test.py".  Should I call the library differently? Or is it a Python3 issue?

I attached the files here.
[gene_cassette.xml.txt](https://github.com/SynBioDex/pySBOL/files/2971056/gene_cassette.xml.txt)
[test.py.txt](https://github.com/SynBioDex/pySBOL/files/2971057/test.py.txt)

**Comment by jakebeal** [comment]
Is this still an issue with pySBOL2? I am closing here, and if it is still an issue, please reopen on pySBOL2.
