### ISSUE TITLE
Need Copy/Import Method that Does Not Require Namespace Parameter

### ISSUE THREAD

**Issue by nroehner** [SynBioDex/pySBOL#90]
Currently, if one wants to make a copy of an object and have it be identified in accordance with their current home namespace (homespace), then they have to pass in the namespace of the object that they are copying. While this enables developers to selectively copy some objects into the current homespace while keeping other copies in their current namespace, it also requires that developers use a library method (or parse out themselves) the namespaces of the objects being copied, and thus requires error handling code for when the URIs of these objects are not SBOL-compliant URIs.

It would be useful to have another copy method that does not require prior-knowledge of the namespace of the object being copied, especially for the case when one wants to import the output of a tool that doesn't use SBOL-compliant URIs into a new namespace.

**Comment by bbartley** [comment]
@nroehner Can you provide an example Document with objects you are trying to import, or some examples of the non-compliant URIs that you are trying to import into a compliant URI?

**Comment by jakebeal** [comment]
Handled in pySBOL2, where the namespace parameter is optional.
