### ISSUE TITLE
get an error when using partShop submit

### ISSUE THREAD

**Issue by jurquiza** [SynBioDex/pySBOL#93]
##when running i don't get the documented behaviour 

shop.submit(doc, overwrite=1)

TypeError: submit() got an unexpected keyword argument 'overwrite'

**Comment by bbartley** [comment]
@jurquiza There is no keyword argument.  Use the syntax:

shop.submit(doc, target_collection_uri, 1)

**Comment by jakebeal** [comment]
I am guessing this resolved the issue; if not, please reopen.
