### ISSUE TITLE
GenBank to SBOL

### ISSUE THREAD

**Issue by bchan** [SynBioDex/pySBOL#95]
I am trying to convert GenBank files to SBOL, but I cannot find anything on the documentation. Is there a way to do this with the library?

**Comment by cjmyers** [comment]
The GenBank to SBOL conversion is done using the Java library libSBOLj.  You can also do this using the SBOLValidator/Converter’s REST API described here:

http://synbiodex.github.io/SBOL-Validator/ <http://synbiodex.github.io/SBOL-Validator/>

I’m not sure if pySBOL has a wrapped interface to this API or not.  Bryan Bartley can likely comment on that.

**Comment by bbartley** [comment]
The head of the develop branch has methods to call the converter API.  Unfortunately, I don't think the package that Ben is using supports it though.

@bchan1298 if you need to convert a small number of files, then the webtool that @cjmyers mentioned should serve your purposes.  If, however, you want to process a large batch of files, or incorporate conversion into an automated pipeline, you will want to use programmatic calls to the converter API.  You can do that by either submitting directly to the converter API using Python's requests package, or I can deploy a new wheel with the latest updates from develop baked in

**Comment by bchan** [comment]
Makes sense. The webtool should be good for my purposes as I am not converting a large batch of files. Thanks for the help!

**Comment by webermarcolivier** [comment]
I would like to implement conversion of Genbank from/to SBOL in an automatic pipeline that we are developing in python for a web application. Calling the web server API is not a good solution in our case. You mentioned that a python wrapper to the SBOL java converter is available, is that correct? I cannot find it in the documentation or in the source code.

**Comment by webermarcolivier** [comment]
@bbartley Is there any chance to see the Genbank to SBOL converter wrapper implemented in pysbol soon? That would help a lot for one of our project and would be greatly appreciated. Thank you for all the work done to develop SBOL tools.

**Comment by bbartley** [comment]
@webermarcolivier see https://pysbol2.readthedocs.io/en/latest/getting_started.html#converting-to-and-from-other-sequence-formats

**Comment by 13anas** [comment]
@bbartley I've tried the online converter but seems not to work.

**Comment by jakebeal** [comment]
Can you expand on the error that you are getting, because this is routine use for other people. Thus, it sounds like it's a more specific bug related to how you're using it, and it would be good to figure out whether the bug is in your code or ours and get it fixed in either case.
